on:
  workflow_dispatch:
  push:
    tags:
      - '*'

name: release
jobs:
  release:
    runs-on: ubuntu-latest
    steps: 
      - name: Get-lastet
        run: |
          echo "LATEST=$(git ls-remote --tag --sort=-v:refname https://github.com/${{ secrets.REPOSITORY }} | head -1 | cut -f 2 | grep -o "[^/]*$")" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
        with:
         repository: ${{ secrets.REPOSITORY }}
         ref: ${{ env.LATEST }}
      - name: Get-version
        id: get_version
        run: |
          #echo "VER=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
          GOVER="$(curl -sLf 'https://golang.org/VERSION?m=text' | grep "go")"
          echo "GO_VERSION=${GOVER#go}" >> $GITHUB_OUTPUT
      - name: Setup-go
        uses: actions/setup-go@v4
        with:
          go-version: '${{ steps.get_version.outputs.GO_VERSION }}'
          check-latest: true
      - name: Get project dependencies
        run: go mod download
      - name: Release
        run: | 
          CGO_ENABLED=0 go build -o release -trimpath -ldflags "-s -w -buildid=" ./main
          zip -9vr release.zip release
      - name: Install minisign and sign
        run: |
          sudo apt-get -y install libsodium-dev
          git clone --depth 1 https://github.com/jedisct1/minisign.git
          cd minisign/src
          mkdir -p /tmp/bin
          cc -O2 -o /tmp/bin/minisign -D_GNU_SOURCE *.c -lsodium
          cd -
          /tmp/bin/minisign -v
          echo "${{ secrets.MINISIGN_SK }}" >> /tmp/minisign.key
          echo | /tmp/bin/minisign -s /tmp/minisign.key -Sm *.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: ./release.zip*
          #tag: ${{ steps.get_version.outputs.VER }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          
  clear:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Check
        id: clear
        run: |
          echo "ACHIVE=$(git ls-remote --tag --sort=-v:refname https://github.com/${{ github.repository }} | head -2 | cut -f 2 | sed -n 2p)" >> $GITHUB_OUTPUT 
          echo "TAG=${ACHIVE##*/}" >> $GITHUB_OUTPUT
      - name: Clear
        run: |
          git clone --quiet https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} tmp
          cd tmp 
          git tag -d ${{ steps.clear.outputs.TAG }}
          git remote add tmp https://${{ github.actor }}:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git config user.name jueyn
          git config user.email 129744577+jueyn@users.noreply.github.com
          git push tmp :${{ steps.clear.outputs.ACHIVE }}
          
  delete-draft:
    needs: clear
    runs-on: ubuntu-latest
    steps:
      - name: Delete drafts
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          
